using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Reto.Data
{
    public static class DataCreator
    {
        public static IEnumerable<(int id, string palabra, string definicion)> GetPalabrasRaras()
        {
            yield return (1, "Abacería", "Tienda de comestibles");
            yield return (2, "Abalear", "Separar del grano ya aventado los residuos de la paja");
            yield return (3, "Abarca", "Calzado rústico, sandalias");
            yield return (4, "Abarrotes", "Artículos de uso doméstico");
            yield return (5, "Abate", "Eclesiástico extranjero, francés o italiano");
            yield return (6, "Aberrar", "Desviarse de lo natural");
            yield return (7, "Abigarrar", "Combinar colores diversos con mal efecto");
            yield return (8, "Abjurar", "Renegar de una creencia u opinión con juramento");
            yield return (9, "Ablación", "Castración femenina por extirpación del clítoris");
            yield return (10, "Ablución", "Acto de lavarse");
            yield return (11, "Abocar", "Verter el contenido de un recipiente en otro acercando las bocas.Besar");
            yield return (12, "Abominar", "Condenar,maldecir");
            yield return (13, "Aborregarse", "Cubrirse el cielo de nubes blanquecinas");
            yield return (14, "Abrótano", "Arbusto de olor penetrante");
            yield return (15, "Absceso", "Bolsa de pus en tejidos orgánicos");
            yield return (16, "Abyección", "Cualidad de ser despreciable");
            yield return (17, "Acanto", "Hierba de hojas rizadas y espinosas, Adorno imitativo de las hojas de esta planta");
            yield return (18, "Acecinar", "Salar cualquier tipo de carne ahumada");
            yield return (19, "Acéfalo", "Sin guía");
            yield return (20, "Aceituno", "Olivo");
            yield return (21, "Acémila", "Mulo o burra de carga");
            yield return (22, "Acíbar", "Sustancia amarga");
            yield return (23, "Acoquinar", "Acobardar");
            yield return (24, "Ácrata", "Anarquista");
            yield return (25, "Acular", "Arrimar por detrás un animal o vehículo");
            yield return (26, "Ad litteram", "Al pie de la letra");
            yield return (27, "Adalid", "Persona que se distingue en la defensa de algo");
            yield return (28, "Adarga", "Escudo");
            yield return (29, "Adarme", "Porción mínima");
            yield return (30, "Adefesio", "Extravagancia");
            yield return (31, "Aditamento", "Añadidura, complemento");
            yield return (32, "Adlátere", "Subordinado muy allegado al superior");
            yield return (33, "Admonición", "Amonestación");
            yield return (34, "Adocenado", "Vulgar");
            yield return (35, "Adscribir", "Atribuir, asignar");
            yield return (36, "Adventicio", "Órgano desarrollado en sitio distinto del natural");
            yield return (37, "Advocación", "Título que se da a templo, altar o imagen particular");
            yield return (38, "Afasia", "Trastorno que dificulta la capacidad de expresión");
            yield return (39, "Afeite", "Maquillaje");
            yield return (40, "Aforar", "Calcular la capacidad de un recipiente");
            yield return (41, "Agón", "Lucha deportiva");
            yield return (42, "Ágora", "Plaza donde se reúnen los ciudadanos para tratar asuntos comunes");
            yield return (43, "Agraz", "uvas sin madurar");
            yield return (44, "Agreste", "Relativo al campo");
            yield return (45, "Aguachirle", "Licor rebajado de ínfima calidad");
            yield return (46, "Aherrojar", "Aprisionar");
            yield return (47, "Ajorca", "Argolla usada como adorno de brazos o piernas");
            yield return (48, "Ajumar", "Emborrachar");
            yield return (49, "Alabastro", "Piedra blanca, traslúcida y compacta");
            yield return (50, "Alar", "Alero");
            yield return (51, "Albar", "De color blanco");
            yield return (52, "Albedo", "Capacidad de reflexión de una superficie");
            yield return (53, "Alberca", "Cisterna artificial de agua");
            yield return (54, "Albor", "Blancura");
            yield return (55, "Albricias", "Felicitaciones por una buena noticia");
            yield return (56, "Albur", "Contingencia, azar");
            yield return (57, "Alcancía", "hucha");
            yield return (58, "Alcázar", "Fortaleza, recinto fortificado");
            yield return (59, "Alcor", "Colina, collado");
            yield return (60, "Alcuza", "Vasija para el aceite");
            yield return (61, "Alfaguara", "Manantial copioso");
            yield return (62, "Alféizar", "Repisa de una ventana, especialmente si se pueden apoyar los codos en ella");
            yield return (63, "Alfeñique", "Persona débil");
            yield return (64, "Algarada", "Alboroto");
            yield return (65, "Algolágnico activo", "Sádico");
            yield return (66, "Algolágnico pasivo", "Masoca");
            yield return (67, "Alharaca", "Demostración exagerada de la vehemencia de un sentimiento");
            yield return (68, "Alícuota", "Proporcional");
            yield return (69, "Alien", "Extraño");
            yield return (70, "Alienígena", "Extranjero");
            yield return (71, "Alijo", "Acción de desmbarcar la carga de una nave");
            yield return (72, "Aljibe", "Cisterna");
            yield return (73, "Almodóvar", "Plaza fortificada");
            yield return (74, "Almoneda", "Subasta de bienes");
            yield return (75, "Alocución", "Discurso breve");
            yield return (76, "Aluvión", "Inundación");
            yield return (77, "Álveo", "Lecho del río");
            yield return (78, "Amarterarse", "Adoptar actitud cariñosa dos enamorados");
            yield return (79, "Amojamar", "Hacer cecina de atún");
            yield return (80, "Amolar", "Fastidiar, aguzar objetos cortantes con la muela");
            yield return (81, "Amollar", "Ceder, desistir");
            yield return (82, "Amover", "Destituir");
            yield return (83, "Amplexación", "Acto sexual, coito");
            yield return (84, "Anacoluto", "Defecto en la unión de las partes de la oración");
            yield return (85, "Anacoreta", "Asceta que vive en un lugar solitario dedicado a la oración");
            yield return (86, "Análogo", "Semejante");
            yield return (87, "Anaquel", "Estante");
            yield return (88, "Anatema", "Maldición");
            yield return (89, "Andrómina", "Embuste, enredo");
            yield return (90, "Aneurisma", "Dilatación de un vaso sanguíneo");
            yield return (91, "Anfibología", "Palabra con doble sentido");
            yield return (92, "Angora", "Relativo a ciertos animales con pelo muy abundante y sedoso");
            yield return (93, "Anonadar", "Humillar, abatir");
            yield return (94, "Antinomia", "Contradicción entre dos principios o leyes");
            yield return (95, "Aparar", "Disponer las manos u otra cosa para recibir algo que se da o hecha");
            yield return (96, "Aparato", "Traducción del vocablo ruso Aparat, que significa dirigentes");
            yield return (97, "Aparcería", "Convenio por el cual una persona cede a otra el disfrute de unos bienes a cambio de parte alícuota de las ganancias");
            yield return (98, "Apeo", "Cortar un árbol, deslindar un finca");
            yield return (99, "Apepsia", "Ausencia de digestión");
            yield return (100, "Ápice", "Extremo superior o punta de una cosa");
            yield return (101, "Apócrifo", "Sin autentificar");
            yield return (102, "Apología", "Discurso o escrito en justificación, defensa o alabanza de alguien o algo");
            yield return (103, "Apoquinar", "Entregar de mala voluntad aquello que corresponde dar o pagar");
            yield return (104, "Apóstata", "Individuo que reniega de su religión, (Desde el punto de vista de los que permanecen en la religión renegada)");
            yield return (105, "Apóstrofe", "Interpelación brusca y poco amable");
            yield return (106, "Apoteosis", "Glorificación, exaltación de una persona");
            yield return (107, "Aprisco", "Lugar donde se recoge el ganado");
            yield return (108, "Apropincuarse", "Acercarse");
            yield return (109, "Arcano", "Incomprensible");
            yield return (110, "Ardite", "Moneda de poco valor");
            yield return (111, "Arpado", "Dícese del arma cuyo filo presenta dientecillos puntiagudos");
            yield return (112, "Arpeo", "Garfio que en combinación con una cuerda se arroja sobre un muro para trepar por él");
            yield return (113, "Arrebol", "Color rojo de las mejillas");
            yield return (114, "Arredrar", "Intimidar");
            yield return (115, "Arreo", "Atavío, adorno");
            yield return (116, "Asaz", "Bastante");
            yield return (117, "Aserción", "Afirmación, Aserto");
            yield return (118, "Astenia", "Falta o pérdida de fuerza");
            yield return (119, "Atafagar", "Sofocar, Aturdir con olores fuertes");
            yield return (120, "Atarugar", "Atestar, Henchir");
            yield return (121, "Atávico", "Aparición en un descendiente de caracteres de un antepasado, Costumbres hereditarias");
            yield return (122, "Atlante", "Columna o soporte con forma masculina");
            yield return (123, "Atolladero", "Lugar donde se atascan los vehículos o personas");
            yield return (124, "Atrabiliario", "Iracundo, con temperamento colérico");
            yield return (125, "Aura", "Viento suave y apacible");
            yield return (126, "Avatar", "Transformación, cambio, vicisitud");
            yield return (127, "Aviar", "Arreglar, prestar");
            yield return (128, "Azabache", "Lignito compacto y de color intensamente negro");
            yield return (129, "Azogue", "Mercurio");
            yield return (130, "Azumbre", "Medida de capacidad equivalente a cuatro litros");
            yield return (131, "Azur", "Azul oscuro");
            yield return (132, "Babieca", "Persona poco inteligente");
            yield return (133, "Badana", "Piel de carnero");
            yield return (134, "Badulaque", "Persona necia e informal");
            yield return (135, "Banquisa", "Conjunto de hielos formados por la congelación del agua del mar en las zonas polares");
            yield return (136, "Barbarismo", "Vocablo extranjero introducido en el idioma");
            yield return (137, "Barbián", "Persona de carácter desenvuelto y simpático");
            yield return (138, "Barragana", "Mujer que convive maritalmente con un hombre sin que medie matrimonio");
            yield return (139, "Barrito", "Llamada del elefante y el rinoceronte");
            yield return (140, "Basca", "Náusea, Furia que siente el animal rabioso en el momento de atacar");
            yield return (141, "Berserk", "Guerrero vikingo de extrema ferocidad, Se cree que en realidad eran enfermos mentales");
            yield return (142, "Blenorragia", "Infección de las vías genitourinarias");
            yield return (143, "Boato", "Ostentación en el porte exterior");
            yield return (144, "Bocoy", "Envase de 600 litros destinado al transporte de vino");
            yield return (145, "Bodrio", "Guiso mal aderezado");
            yield return (146, "Bofe", "Pulmón");
            yield return (147, "Borborigmo", "Ruido producido por los movimientos peristálticos intestinales");
            yield return (148, "Bóreas", "Viento del norte");
            yield return (149, "Bramante", "Cordel delgado de cáñamo");
            yield return (150, "Brete", "Cepo de hierro que se coloca en los pies");
            yield return (151, "Bufar", "Manifestar enojo");
            yield return (152, "Cabestro", "Buey manso que se utiliza para facilitar el manejo del ganado bravío");
            yield return (153, "Cabildo", "Comunidad de los canónigos de una iglesia catedral");
            yield return (154, "Cachaba", "Cayado");
            yield return (155, "Cachaza", "Flema");
            yield return (156, "Cachazudo", "Flemático");
            yield return (157, "Cacumen", "Agudeza, perspicacia");
            yield return (158, "Caletre", "Inteligencia");
            yield return (159, "Calígino", "Niebla, oscuridad");
            yield return (160, "Camama", "Embuste");
            yield return (161, "Canguelo", "Miedo, temor");
            yield return (162, "Canícula", "Época del año en la que el calor es más fuerte");
            yield return (163, "Capcioso", "Engañoso, que conduce a error");
            yield return (164, "Caporal", "Capataz");
            yield return (165, "Carpanta", "Hambre violenta");
            yield return (166, "Carpetovetónico", "Arraigadamente español, con desprecio de lo extranjero");
            yield return (167, "Casorio", "Casamiento mal concertado o de poco lucimiento");
            yield return (168, "Castrametación", "Arte y Ciencia de disponer a las tropas en lugares habitables, cuarteles, campamentos");
            yield return (169, "Casuística", "Parte de la teología que trata de los casos de conciencia");
            yield return (170, "Catarsis", "Purificación de las pasiones por medio del goce de obras estéticas");
            yield return (171, "Catecúmeno", "El que preconiza la catequesis para los adultos");
            yield return (172, "Caterva", "Multitud de personas o cosas en desorden");
            yield return (173, "Catilinario", "Dícese del discurso vehemente dirigido contra alguien");
            yield return (174, "Cazalla", "Aguardiente anisado");
            yield return (175, "Céfiro", "Viento del oeste");
            yield return (176, "Celar", "Vigilar con particular cuidad el cumplimiento de las leyes");
            yield return (177, "Chacota", "Broma o burla");
            yield return (178, "Chafarrinada", "Mancha");
            yield return (179, "Chalán", "Persona poco escrupulosa o que trata en ganados");
            yield return (180, "Chamarilero", "Persona que comercia con objetos usados");
            yield return (181, "Chamba", "Casualidad favorable, Acierto casual");
            yield return (182, "Chanfaina", "Guiso de varios elementos troceados");
            yield return (183, "Charrán", "Pillo, tunante");
            yield return (184, "Chasca", "Leña menuda procedente de la poda");
            yield return (185, "Chascarrillo", "Anécdota");
            yield return (186, "Chicoleo", "Piropo");
            yield return (187, "Chipén", "Excelente");
            yield return (188, "Chiquero", "Choza donde se recogen los puercos");
            yield return (189, "Chiquilicuatro", "Persona insignificante");
            yield return (190, "Chirimbolo", "Utensilio, vasija");
            yield return (191, "Chirinola", "Discusión acalorada");
            yield return (192, "Chirivita", "Chispa, Lucecillas que se ven por alguna anormalidad en los ojos");
            yield return (193, "Chirlo", "Herida prolongada en la cara, cicatriz de la misma");
            yield return (194, "Chisguete", "Trago de vino");
            yield return (195, "Choto", "Cría de la cabra mientras aún mama, Ternero");
            yield return (196, "Cimarrón", "Animal doméstico que huye al campo y se hace montaraz");
            yield return (197, "Circuir", "Rodear, cercar");
            yield return (198, "Circunloquio", "Rodeo o digresión antes de entrar en materia");
            yield return (199, "Cisoria", "Arte , Arte de trinchar las viandas");
            yield return (200, "Climaterio", "Época de la vida en la que empieza la progresiva declinación de todas las funciones");
            yield return (201, "Codicilo", "Disposición de última voluntad");
            yield return (202, "Coercer", "Contener, refrenar");
            yield return (203, "Cofa", "Plataforma situada en lo alto de los palos de las embarcaciones");
            yield return (204, "Cogitabundo", "Muy pensativo");
            yield return (205, "Colación", "Comida ligera");
            yield return (206, "Columbrar", "Atisbar, vislumbrar");
            yield return (207, "Complutense", "Relativo a Alcalá de Henares");
            yield return (208, "Conato", "Amago");
            yield return (209, "Concitar", "Excitar los sentimientos de uno contra otro");
            yield return (210, "Concomerse", "Consumirse de impaciencia, arrepentimiento o envidia");
            yield return (211, "Concomitancia", "Simultaneidad de unas cosas con otras");
            yield return (212, "Concrectación", "Acto sexual, incluyendo pero no limitándose al coito");
            yield return (213, "Confalón", "Banderín");
            yield return (214, "Congruente", "Dícese de aquello cuyas partes están en armonía y acuerdo");
            yield return (215, "Conminar", "Amenazar con alguna pena o castigo");
            yield return (216, "Connivencia", "Acción de confabularse");
            yield return (217, "Contemporizar", "Acomodarse, refrenarse");
            yield return (218, "Contingente", "Que puede suceder o no suceder");
            yield return (219, "Contubernio", "Amancebamiento");
            yield return (220, "Contumaz", "Porfiado y tenaz en mantener algún error");
            yield return (221, "Craso", "Grueso, gordo o espeso");
            yield return (222, "Crencha", "Raya que divide el pelo en dos partes");
            yield return (223, "Creso", "Personaje de la antigüedad famoso por su riqueza");
            yield return (224, "Cristomatía", "Colección de escritos escogidos con finalidad didáctica");
            yield return (225, "Cuchufleta", "Broma o chanza");
            yield return (226, "Cuesco", "Pedo ruidoso");
            yield return (227, "Cutáneo", "Relativo a la piel");
            yield return (228, "Dable", "Posible");
            yield return (229, "Dádivas", "Regalos, presentes");
            yield return (230, "Deán", "Párroco de la parroquia más importante de la ciudad");
            yield return (231, "Dechado", "Modelo, ejemplo");
            yield return (232, "Degollina", "Matanza, mortandad");
            yield return (233, "Deleznable", "Que se rompe o deshace fácilmente, Inconsistente");
            yield return (234, "Delicuescencia", "Propiedad que tienen ciertos cuerpos de disgregarse al contacto con la humedad del aire, Degradación de las normas morales");
            yield return (235, "Demiurgo", "Ordenador divino del Cosmos");
            yield return (236, "Denostar", "Injuriar gravemente");
            yield return (237, "Denuesto", "Insulto, ofensa");
            yield return (238, "Deontología", "Ciencia de los deberes");
            yield return (239, "Depauperar", "Debilitar física o moralmente");
            yield return (240, "Deprecación", "Plegaria");
            yield return (241, "Desacatar", "Faltar a la reverencia o al respeto");
            yield return (242, "Desaforado", "Grande con exceso");
            yield return (243, "Desafuero", "Acto violento contra la ley, la justicia o la vida. Hecho que priva de fuero o competencia jurisdiccional al que la tenía.");
            yield return (244, "Desaguisado", "Hecho contra la ley o la razón");
            yield return (245, "Descabalar", "Quitar o perder alguna de las partes precisas para construir una cosa completa");
            yield return (246, "Descalabradura", "Herida en la cabeza, cicatriz de la misma");
            yield return (247, "Descastado", "Que muestra poco cariño hacia los parientes");
            yield return (248, "Descrismar", "Golpear a alguien con fuerza en la cabeza");
            yield return (249, "Descuajaringar", "Desunir, desvencijar");
            yield return (250, "Desenconar", "Desinflamar, Apaciguar");
            yield return (251, "Desfogar", "Exteriorizar una pasión");
            yield return (252, "Desgaire", "Descuido");
            yield return (253, "Desiderátum", "Objeto de un vivo deseo");
            yield return (254, "Desleír", "Disolver en un líquido");
            yield return (255, "Desliar", "Deshacer un paquete");
            yield return (256, "Deslomar", "Agotar");
            yield return (257, "Desmadrarse", "Pasarse de los límites acostumbrados");
            yield return (258, "Desmanotado", "Torpe");
            yield return (259, "Desmedro", "Decaimiento");
            yield return (260, "Despotricar", "Hablar sin consideración");
            yield return (261, "Detrimento", "Daño, perjuicio");
            yield return (262, "Deyección", "Excremento");
            yield return (263, "Diatriba", "Discurso violento");
            yield return (264, "Diletante", "Amateur");
            yield return (265, "Dipsomanía", "Alcoholismo");
            yield return (266, "Discente", "Que recibe enseñanzas");
            yield return (267, "Dislate", "Disparate");
            yield return (268, "Disloque", "El colmo, en grado sumo");
            yield return (269, "Disnea", "Dificultad respiratoria");
            yield return (270, "Dispepsia", "Trastorno gástrico doloroso");
            yield return (271, "Ditirambo", "Poema en honor de Dionisos, Alabanza exagerada");
            yield return (272, "Dolo", "Engaño");
            yield return (273, "Duela", "Cada una de las tablas curvas que forman las paredes de un tonel o barrica");
            yield return (274, "E", "");
            yield return (275, "Ebúrneo", "Relativo al marfil");
            yield return (276, "Eclecticismo", "Doctrina que consiste en escoger de un cuerpo de doctrinas aquellos aspectos más favorables");
            yield return (277, "Égida", "Escudo, arma defensiva");
            yield return (278, "Egregio", "Insigne, ilustre");
            yield return (279, "Ejido", "Terreno inculto");
            yield return (280, "Elidir", "Suprimir el elemento vocálico final ante la vocal inicial de la palabra siguiente");
            yield return (281, "Emascular", "Castrar");
            yield return (282, "Embelecar", "Engañar con halagos");
            yield return (283, "Empedernido", "Muy arraigado");
            yield return (284, "Emperrarse", "Empeñarse");
            yield return (285, "Empíreo", "Cielo, paraíso");
            yield return (286, "Emplaste", "Componenda poco satisfactoria, Persona de poca salud");
            yield return (287, "Emporio", "Lugar donde concurrían para el comercio gente de diversas naciones");
            yield return (288, "Empreñar", "Molestar, fastidiar");
            yield return (289, "Encalabrinar", "Irritar");
            yield return (290, "Enclenque", "Raquítico");
            yield return (291, "Encono", "Rencor");
            yield return (292, "Endemia", "Enfermedad permanente y localizada en una región geográfica");
            yield return (293, "Energúmeno", "Persona encolerizada que grita mucho");
            yield return (294, "Enjundia", "Lo más sustancioso e importante de algo inmaterial");
            yield return (295, "Ensalmar", "Componer hueso roto");
            yield return (296, "Ensalmo", "Rezo curativo");
            yield return (297, "Entelequia", "Realidad que ha llegado al estado de perfección");
            yield return (298, "Entente", "Acuerdo");
            yield return (299, "Entreoír", "Oír algo sin entender");
            yield return (300, "Entronizar", "Ensalzar, Colocar a alguien en el trono");
            yield return (301, "Entronque", "Contraer parentesco");
            yield return (302, "Envite", "Apuesta");
            yield return (303, "Epatar", "Deslumbrar");
            yield return (304, "Epígono", "El que sigue las huellas de otro en materia artística, filosófica o científica");
            yield return (305, "Epistemiología", "Teoría del conocimiento o saber científico");
            yield return (306, "Epitalamio", "Composición lírica en celebración de una boda");
            yield return (307, "Epítome", "Compendio de una obra extensa en el que sólo se expone lo más fundamental");
            yield return (308, "Erisipela", "Enfermedad infecciosa");
            yield return (309, "Escandallo", "Determinación del precio de coste de una mercancía");
            yield return (310, "Escindir", "Dividir");
            yield return (311, "Escolio", "Nota que se pone a un texto para explicarlo");
            yield return (312, "Escuálido", "Delgado");
            yield return (313, "Esmegma", "Secreción blanquecina del bálano");
            yield return (314, "Espiche", "Discurso, arenga");
            yield return (315, "Espirituoso", "Que contiene una importante cantidad de alcohol");
            yield return (316, "Esplenomegalia", "Inflamación del bazo");
            yield return (317, "Esputo", "Secreción de las vías respiratorias");
            yield return (318, "Esquirol", "Obrero que no sigue la orden de huelga");
            yield return (319, "Estafermo", "Persona que se queda embobada");
            yield return (320, "Estantigua", "Persona alta, desgarbada y mal vestida");
            yield return (321, "Estenosis", "Estrechez patológica de un conducto u orificio");
            yield return (322, "Estero", "Zona del litoral inundada durante la pleamar");
            yield return (323, "Estevado", "Que tiene las piernas torcidas");
            yield return (324, "Estigma", "Marca o señal en el cuerpo");
            yield return (325, "Estilita", "Que vive en lo alto de una columna");
            yield return (326, "Estipendio", "Remuneración");
            yield return (327, "Estólido", "Bobo");
            yield return (328, "Estro", "Inspiración artística");
            yield return (329, "Estulto", "Necio");
            yield return (330, "Estupro", "Violación de una mujer menor de edad");
            yield return (331, "Evanescente", "Que se desvanece");
            yield return (332, "Ex aequo", "En igualdad de méritos");
            yield return (333, "Exabrupto", "Salida de tono");
            yield return (334, "Exangüe", "Sin fuerzas");
            yield return (335, "Exánime", "Muerto");
            yield return (336, "Excelso", "De elevada categoría espiritual");
            yield return (337, "Excrecencia", "Cualquier adherencia superflua");
            yield return (338, "Execrable", "Digno de abominación");
            yield return (339, "Exégesis", "Translación de una forma artística a otro medio");
            yield return (340, "Exequias", "Ceremonias religiosas por un difunto");
            yield return (341, "Eximio", "Muy excelente");
            yield return (342, "Exonerar", "Destituir a alguien, Librar de una carga");
            yield return (343, "Exordio", "Introducción");
            yield return (344, "Expugnar", "Tomar por fuerza alguna plaza");
            yield return (345, "Extricar", "Desenredar");
            yield return (346, "Exudar", "Salir un líquido fuera de sus vasos continentes");
            yield return (347, "Exvoto", "Ofrenda a la divinidad en señal de agradecimiento");
            yield return (348, "Eyectar", "Proyectar al exterior");
            yield return (349, "Facticio", "Que no es natural");
            yield return (350, "Factótum", "Persona de plena confianza de otra y desempeña así sus funciones");
            yield return (351, "Facundia", "Exageración o facilidad de palabra");
            yield return (352, "Falcado", "Provisto de hoces o con forma de hoz");
            yield return (353, "Fanal", "Linterna");
            yield return (354, "Fardel", "Morral");
            yield return (355, "Farmacopea", "Libro de recetas medicinales");
            yield return (356, "Fasto", "Memorable, venturoso");
            yield return (357, "Fastos", "Anales de sucesos venturosos");
            yield return (358, "Fatídico", "Que vaticina el porvenir, anunciando desgracias");
            yield return (359, "Fausto", "Que causa alegría o felicidad, Suntuosidad");
            yield return (360, "Felón", "Fementido");
            yield return (361, "Fementido", "Falto de fe y palabra");
            yield return (362, "Fenecer", "Concluir, Morir");
            yield return (363, "Feraz", "Cultivos o tierras muy fértiles");
            yield return (364, "Férula (Bajo la)", "Bajo la dominación");
            yield return (365, "Fetén", "Verdad, Verdadero, Auténtico");
            yield return (366, "Fideicomiso", "Donación testamentaria para ser transmitida o invertida como se señala");
            yield return (367, "Fiduciario", "Encargado de un fideicomiso");
            yield return (368, "Fígaro", "Barbero");
            yield return (369, "Figón", "Taberna");
            yield return (370, "Filípica", "Discurso arengante, Invectiva");
            yield return (371, "Filis", "Gracia");
            yield return (372, "Filosofastro", "Persona que pretende filosofar siendo inane");
            yield return (373, "Flámula", "Banderola");
            yield return (374, "Flete", "Precio que se paga por un buque, Carga del mismo");
            yield return (375, "Florilegio", "Colección de fragmentos literarios selectos");
            yield return (376, "Floripondio", "Adorno de mal gusto");
            yield return (377, "Fomento", "Medicamento o líquido de uso externo que se aplica con compresas calientes, Linimento");
            yield return (378, "Forúnculo", "Inflamación del folículo piloso");
            yield return (379, "Francachela", "Fiesta etílico-lúdica");
            yield return (380, "Frenopatía", "Siquiatría");
            yield return (381, "Friabilidad", "Propiedad de ser fácilmente desmenuzable");
            yield return (382, "Frivolité", "Encaje");
            yield return (383, "Frugívoro", "Que se alimenta de frutos");
            yield return (384, "Fuer de", "A título de");
            yield return (385, "Fuero", "Derechos o privilegios concedidos a un territorio o persona. Compilación de leyes.");
            yield return (386, "Ful", "fallido, falso, de poco valor");
            yield return (387, "Fumata", "columna de humo");
            yield return (388, "Fútil", "Sin valor");
            yield return (389, "Galbana", "Pereza");
            yield return (390, "Galimatías", "Lenguaje oscuro por la impropiedad de la frase o por la confusión de las ideas");
            yield return (391, "Gallardete", "Banderola");
            yield return (392, "Gañán", "Mozo de labranza");
            yield return (393, "Gañir", "Aullido lastimero");
            yield return (394, "Garambaina", "Adorno de mal gusto, Gestos afectados");
            yield return (395, "Garlito", "Trampa");
            yield return (396, "Garlo", "Ave que canta o gorjea mucho, Persona que habla mucho");
            yield return (397, "Garrulería", "Charla de persona garla");
            yield return (398, "Gazmoño", "Que finge devoción o escrúpulos que no tiene");
            yield return (399, "Gaznápiro", "Palurdo");
            yield return (400, "Gazuza", "Hambre");
            yield return (401, "Gerifalte", "Persona que sobresale en cierto cargo, Ave rapaz");
            yield return (402, "Gleba", "Tierras a las que están adscritos los siervos");
            yield return (403, "Gollería", "Manjares delicados");
            yield return (404, "Goniómetro", "Instrumento para medir ángulos");
            yield return (405, "Gorigori", "Ruido producido por personas que hablan a la vez");
            yield return (406, "Grey", "Rebaño");
            yield return (407, "Grímpola", "Insignia militar");
            yield return (408, "Guija", "Guijarro");
            yield return (409, "Guiñapo", "Andrajo");
            yield return (410, "Guirigay", "Barullo");
            yield return (411, "Gusarapo", "Animalillos molestos que habitan en medios líquidos");
            yield return (412, "Guti", "Pueblo del norte de Mesopotamia, invasor del imperio Acadio");
            yield return (413, "Hecatombe", "Desastre con muchas víctimas, Sacrifico");
            yield return (414, "Hediondo", "Pestilente");
            yield return (415, "Hélade", "Grecia e islas del mar Egeo");
            yield return (416, "Heresiarca", "Promotor de una herejía");
            yield return (417, "Hermeneuta", "Persona que interpreta textos para fijar su verdadero sentido");
            yield return (418, "Hero y Leandro", "Famosos amantes de la antigüedad, Leandro atravesaba a nado cada día el Helesponto para ver a Hero");
            yield return (419, "Hesitación", "Duda");
            yield return (420, "Hetaira", "Ramera");
            yield return (421, "Hidropesía", "Acumulación patológica de líquidos");
            yield return (422, "Hielo seco", "CO2 en estado sólido");
            yield return (423, "Higa", "Gesto despreciativo");
            yield return (424, "Himen", "Virgo");
            yield return (425, "Himeneo", "Boda");
            yield return (426, "Hiperbóreo", "Nórdico, Regiones próximas al polo norte");
            yield return (427, "Hipererosia", "Exceso patológico de libido");
            yield return (428, "Hisopear", "Rociar con agua bendita");
            yield return (429, "Histrión", "Actor");
            yield return (430, "Hontanar", "Sitio en el que nacen fuentes");
            yield return (431, "Hoplita", "Infante pesado griego");
            yield return (432, "Hopo", "Cola lanuda o peluda");
            yield return (433, "Hornacina", "Hueco para contener imágenes");
            yield return (434, "Hortera", "Dependiente, Persona que quiere aparentar más de lo que es");
            yield return (435, "Hozar", "Meter las narices en algo");
            yield return (436, "Humectación", "Acción y efecto de humedecer");
            yield return (437, "Husmear", "Olfatear");
            yield return (438, "Íbex o Íbice", "Mamífero rumiante que vive en las montañas españolas");
            yield return (439, "Icono", "Pintura religiosa realizada sobre una tabla");
            yield return (440, "Ídem", "Lo mismo o el mismo");
            yield return (441, "Idílico", "sumamente placentero o agradable");
            yield return (442, "Idiocia", "Retraso mental");
            yield return (443, "Idiotismo", "Construcción peculiar de un idioma");
            yield return (444, "Idóneo", "Apto");
            yield return (445, "Ignominia", "Deshonra, pérdida del respeto ajeno");
            yield return (446, "Ignoto", "No conocido ni descubierto");
            yield return (447, "Ijada", "Ijar, Espacio entre las falsas costillas y la cadera");
            yield return (448, "Ilación", "Relación entre ideas que se deducen unas de otras");
            yield return (449, "Ilicitano", "De Elche");
            yield return (450, "Ilícito", "Prohibido por la ley");
            yield return (451, "Iluso", "Engañado por una ilusión");
            yield return (452, "Imbricación", "Disposición de las tejas, láminas u otros objetos, de modo que uno cubre parcialmente al otro");
            yield return (453, "Imbuir", "Inculcar ciertas ideas o pensamientos");
            yield return (454, "Impar", "Que no tiene par");
            yield return (455, "Impase", "Callejón sin salida, atascamiento");
            yield return (456, "Impedimenta", "Bagaje que lleva la tropa");
            yield return (457, "Impepinable", "Inevitable, indiscutible");
            yield return (458, "Impetrar", "Solicitar una gracia con mucha intensidad");
            yield return (459, "Impositor", "Persona que ingresa dinero en un banco");
            yield return (460, "Imprecación", "Exclamación en la que se expresa el deseo de que a alguien le ocurra algo malo");
            yield return (461, "Imprescriptible", "Que no puede prescribir");
            yield return (462, "Ímprobo", "Esfuerzo o trabajo excesivo y continuado");
            yield return (463, "Impronta", "Señal o carácter peculiar");
            yield return (464, "Improperio", "Injuria de palabra");
            yield return (465, "Imputar", "Atribuir un delito o falta");
            yield return (466, "In albis", "Sin saber ni comprender nada");
            yield return (467, "Inalienable", "Que no se puede enajenar");
            yield return (468, "Inane", "Endeble, insustancial, vano, fútil");
            yield return (469, "Incipiente", "Que comienza");
            yield return (470, "Inciso", "Intercalación en un discurso para tratar un tema alejado del principal");
            yield return (471, "Incitar", "Estimular");
            yield return (472, "Ínclito", "Ilustre");
            yield return (473, "Incoar", "Principiar un sumario, pleito, proceso");
            yield return (474, "Incólume", "Sano, sin menoscabo");
            yield return (475, "Increpar", "Reprender con dureza y severidad");
            yield return (476, "Incriminar", "Culpar de un delito");
            yield return (477, "Incruento", "Sin derramamiento de sangre");
            yield return (478, "Inculcar", "Fijar una idea en la mente a través de sucesivas repeticiones");
            yield return (479, "Incumbir", "Concernir");
            yield return (480, "Incunable", "Impresión de antes del año 1500");
            yield return (481, "Incurrir", "Llevar a cabo una falta u error");
            yield return (482, "Indefectible", "Que no puede dejar de ocurrir");
            yield return (483, "Indeleble", "Que no se puede borrar o quitar");
            yield return (484, "Indesmallable", "Dícese del género de punto en el que una rotura no provoca una carrera");
            yield return (485, "Indígena", "Oriundo del país del que se trata");
            yield return (486, "Indigente", "Que no tiene recursos para vivir");
            yield return (487, "Índigo", "Colorante extraído de las hojas del añil");
            yield return (488, "Índole", "Condición natural de cada uno");
            yield return (489, "Inducir", "Hacer por diversos medios que alguien realice una determinada acción");
            yield return (490, "Indulgencia", "Facilidad en perdonar o conceder gracias");
            yield return (491, "Inefable", "Sin descripción posible");
            yield return (492, "Ineluctable", "Contra el que no se puede luchar");
            yield return (493, "Inenarrable", "Difícil de describir");
            yield return (494, "Inescrutable", "Que no se puede saber o averiguar");
            yield return (495, "Inexorable", "Implacable");
            yield return (496, "Infamar", "Difamar");
            yield return (497, "Infarto", "Necrosis visceral, no necesariamente en el miocardio");
            yield return (498, "Infausto", "Que acompaña o anuncia una desgracia");
            yield return (499, "Infecto", "Maloliente, sucio, repugnante");
            yield return (500, "Inferir", "Sacar una consecuencia de algo");
            yield return (501, "Infestar", "Contaminar, corromper");
            yield return (502, "Infibulación", "Operación consistente en colocar un aro en el pene, con el fin de imposibilitar el coito");
            yield return (503, "Infiernillo", "Aparato con lámpara de alcohol");
            yield return (504, "Ínfimo", "El más bajo, el último");
            yield return (505, "Infligir", "Causar castigo, derrota o agravio");
            yield return (506, "Influenza", "Gripe");
            yield return (507, "Infringir", "Quebrantar una ley");
            yield return (508, "Ínfulas", "Presunción o vanidad");
            yield return (509, "Infundio", "Noticia falsa, chisme");
            yield return (510, "Infundir", "Provocar cierto estado de ánimo");
            yield return (511, "Infusa", "Que se posee de forma natural");
            yield return (512, "Ingente", "Muy grande");
            yield return (513, "Íngrimo", "Solitario");
            yield return (514, "Inhabilitar", "Declarar inhábil para ejercer cargos públicos");
            yield return (515, "Inhibir", "Suspender una función o actividad del organismo mediante un estímulo");
            yield return (516, "Inhóspito", "Poco acogedor");
            yield return (517, "Inhumar", "Enterrar");
            yield return (518, "Inicuo", "Injusto");
            yield return (519, "Ininteligible", "Que no se puede comprender");
            yield return (520, "Iniquidad", "El que es inicuo");
            yield return (521, "Injerirse", "Entrometerse");
            yield return (522, "Injuria", "Atentado contra el honor");
            yield return (523, "Inmanente", "Que es inherente a un ser");
            yield return (524, "Inmarcesible", "Que no se marchita");
            yield return (525, "Inmolar", "Sacrificar");
            yield return (526, "Inmueble", "Bien no transportable, como terrenos o edificios");
            yield return (527, "Inmundicia", "Suciedad, basura");
            yield return (528, "Inocular", "Introducir en el organismo una toxina o patógeno");
            yield return (529, "Inocuo", "Incapaz de dañar");
            yield return (530, "Inopia, estar en la", "Despistado");
            yield return (531, "Inopinado", "Que sucede sin pensar o esperarse");
            yield return (532, "Inquina", "Animadversión");
            yield return (533, "Inri", "Afrenta");
            yield return (534, "Insalubre", "Insano");
            yield return (535, "Insidia", "Acción o palabras llenas de mala intención");
            yield return (536, "Insólito", "Que ocurre rara vez");
            yield return (537, "Insoslayable", "Que no se puede evitar");
            yield return (538, "Instar", "Apremiar, urgir");
            yield return (539, "Instigar", "Incitar, provocar");
            yield return (540, "Instituir", "Fundar");
            yield return (541, "Insuflar", "Introducir soplando");
            yield return (542, "Insulso", "Insípido");
            yield return (543, "Insurgente", "Insurrecto");
            yield return (544, "Inteligible", "comprensible");
            yield return (545, "Ínterin", "Intervalo");
            yield return (546, "Interpelar", "Solicitar de alguien que dé explicaciones");
            yield return (547, "Interregno", "Espacio de tiempo en el que un estado no tiene soberano");
            yield return (548, "Intríngulis", "Dificultad o complicación de una cosa");
            yield return (549, "Inusitado", "Que no es habitual");
            yield return (550, "Invectiva", "Discurso acre y violento contra personas o cosas");
            yield return (551, "Involución", "Proceso regresivo de una situación");
            yield return (552, "Irrisorio", "Que provoca la risa");
            yield return (553, "Irrumación", "Deglución del esperma");
            yield return (554, "Jácaro", "Fanfarrón");
            yield return (555, "Jaez", "Adorno de las caballerías");
            yield return (556, "Jayán", "Persona de gran estatura y mucha fuerza, Rufián");
            yield return (557, "Jerigonza", "Habla especial y enrevesada");
            yield return (558, "Jipiar", "Gemir, gimotear");
            yield return (559, "Jofaina", "Palangana");
            yield return (560, "Joyel", "Joya pequeña");
            yield return (561, "Kefir", "Alimento turco gelatinoso obtenido de la leche");
            yield return (562, "Kosher", "Comida que es aceptable según la Torah");
            yield return (563, "Lábaro", "Estandarte");
            yield return (564, "Labil", "Inestable");
            yield return (565, "Lacustre", "Relativo a un lago");
            yield return (566, "Ladino", "Taimado");
            yield return (567, "Lañar", "Grapar dos piezas");
            yield return (568, "Laos", "Masa primordial de un ejército, especialmente invasor");
            yield return (569, "Laso", "Cansado");
            yield return (570, "Lato", "Extenso o extendido, Significado de una palabra por extensión");
            yield return (571, "Lavativa", "Enema,");
            yield return (572, "Laviérnago", "Arbusto");
            yield return (573, "Laxo", "Flojo, Poco firme o severo");
            yield return (574, "Lazareto", "Establecimiento sanitario en el que se aíslan enfermos contagiosos");
            yield return (575, "Légamo", "Cieno, Lodo pegajoso");
            yield return (576, "Lego", "Novato, Miembro seglar de una orden monástica");
            yield return (577, "Lelo", "Atontado");
            yield return (578, "Lenidad", "Excesiva condescendencia al exigir el cumplimiento de los deberes");
            yield return (579, "Lenocinio", "Alcahuetería");
            yield return (580, "Leñero", "Persona que vende leña");
            yield return (581, "Lerdo", "Torpe");
            yield return (582, "Lesivo", "Dañino");
            yield return (583, "Leso", "Que ha sido dañado, agraviado o lastimado");
            yield return (584, "Libelo", "Escrito difamatorio");
            yield return (585, "Licitar", "Ofrecer un precio por lo que se subasta");
            yield return (586, "Linimento", "Ungüento");
            yield return (587, "Lipotimia", "Desmayo");
            yield return (588, "Litiasis", "Formación de cálculos en diversas estructuras del organismo, p. ej, Riñón");
            yield return (589, "Litri", "Persona excesivamente presuntuosa");
            yield return (590, "Lobanillo", "Tumor quístico superficial no doloroso");
            yield return (591, "Loor", "Alabanza");
            yield return (592, "Lorica o Loriga", "Armadura romana");
            yield return (593, "Lúbrica", "Lujuriosa");
            yield return (594, "Luctuoso", "Triste y digno de llanto");
            yield return (595, "Lucubrar", "Dedicarse a trabajos artísticos, especialmente de noche");
            yield return (596, "Ludibrio", "Escarnio, desprecio");
            yield return (597, "Lupanar", "Prostíbulo");
            yield return (598, "Maca", "Daño ligero que presenta la fruta");
            yield return (599, "Macabro", "Participa de lo terrorífico y repulsivo de la muerte");
            yield return (600, "Macana", "Mentira, embuste");
            yield return (601, "Mácula", "Mancha");
            yield return (602, "Maestral o Mistral", "Viento frío y seco");
            yield return (603, "Magnánimo", "Bondadoso");
            yield return (604, "Malbaratar", "Vender a bajo precio");
            yield return (605, "Malhadado", "Desventurado");
            yield return (606, "Malquerencia", "Antipatía");
            yield return (607, "Mamarracho", "Persona que viste grotescamente y vive de forma ridícula");
            yield return (608, "Mandanga", "Pachorra");
            yield return (609, "Manducar", "Comer");
            yield return (610, "Manubrio", "Empuñadura o manija de un instrumento");
            yield return (611, "Marasmo", "Inmovilidad física o moral");
            yield return (612, "Marchamo", "Señal que los aduaneros ponen en los fardos ya reconocidos");
            yield return (613, "Maremágnum", "Confusión");
            yield return (614, "Marrajo", "Astuto");
            yield return (615, "Marrana", "Parte de la noria que sirve de pivote al resto de la estructura, De ahí la expresión joder la marrana");
            yield return (616, "Martingala", "Artimaña");
            yield return (617, "Mastuerzo", "Necio");
            yield return (618, "Matasiete", "Fanfarrón");
            yield return (619, "Matute", "Contrabando");
            yield return (620, "Maula", "Cosa inútil");
            yield return (621, "Mayéutica", "Método socrático de enseñanza");
            yield return (622, "Mefítico", "Maloliente");
            yield return (623, "Mejunje", "Bebida, cosmético o líquido de aspecto desagradable");
            yield return (624, "Melopea", "Melodía");
            yield return (625, "Ménade", "Bacante, Mujer frenética");
            yield return (626, "Mercachifle", "Persona dominada por el mercantilismo");
            yield return (627, "Mesalina", "Hetaira");
            yield return (628, "Metástasis", "Extensión de las lesiones por el organismo");
            yield return (629, "Metempsicosis", "Acto por el cual un alma abandona un cuerpo para entrar en otro");
            yield return (630, "Miasma", "Nube de pestilencia");
            yield return (631, "Mies", "Trigo maduro antes de la siega");
            yield return (632, "Milicia", "Ejército no permanente");
            yield return (633, "Misacantano", "Sacerdote que dice o canta misa por primera vez");
            yield return (634, "Moción", "Proposición que se hace a una asamblea o congreso");
            yield return (635, "Mofa", "Burla que se hace con destreza");
            yield return (636, "Mojigato", "Gazmoño");
            yield return (637, "Molturar", "Moler");
            yield return (638, "Mondongo", "Intestinos y panza de un animal");
            yield return (639, "Mórbido", "Suave, blanco, delicado");
            yield return (640, "Morboso", "Insano");
            yield return (641, "Morganático", "Matrimonio de una persona de alta dignidad con otra de más baja categoría");
            yield return (642, "Morigerar", "Moderar los excesos");
            yield return (643, "Morondo", "Pelado");
            yield return (644, "Morralla", "Conjunto de personas despreciables, Cosas sin valor");
            yield return (645, "Mostrenco", "Bienes muebles o inmuebles abandonados o sin dueño");
            yield return (646, "Muermo", "Enfermedad del ganado caballar que produce úlceras");
            yield return (647, "Municiones de boca", "Provisiones");
            yield return (648, "Murria", "Abatimiento, melancolía");
            yield return (649, "Nadir", "Punto opuesto al cenit");
            yield return (650, "Nefando", "Abominable");
            yield return (651, "Nepotismo", "Abuso de poder favoreciendo a parientes o amigos");
            yield return (652, "Neurastenia", "Alteración del sistema nervioso que provoca fatiga crónica");
            yield return (653, "Nimio", "Insignificante");
            yield return (654, "Núbil", "En edad de contraer matrimonio");
            yield return (655, "Óbice", "Inconveniente u obstáculo");
            yield return (656, "Óbito", "Defunción");
            yield return (657, "Oblación", "Ofrenda");
            yield return (658, "Oblongo", "Más largo que ancho");
            yield return (659, "Obnubilar", "Ofuscar");
            yield return (660, "Obsoleto", "Viejo, Caduco, Pasado de moda, Inútil por vejez");
            yield return (661, "Oleaginoso", "Aceitoso, Con textura de aceite");
            yield return (662, "Ológrafo", "Dícese del testamento de puño y letra del testador");
            yield return (663, "Omnímodo", "Total");
            yield return (664, "Onagro", "Burro salvaje de las estepas asiáticas, Oneroso, Pesado, Que ocasiona gastos");
            yield return (665, "Onán", "Rey bíblico que tiraba su esperma al suelo para no tener descendencia,");
            yield return (666, "Onanismo", "Masturbación");
            yield return (667, "Opérculo", "Tapón para ciertos orificios de animales");
            yield return (668, "Opúsculo", "Obra impresa de corta extensión");
            yield return (669, "Orate", "Persona de poco juicio");
            yield return (670, "Oriflama", "Pendón, banderola");
            yield return (671, "Orín", "Óxido de los metales corroídos");
            yield return (672, "Oropel", "Adorno de poco valor y mucha apariencia");
            yield return (673, "Pachanga", "Jolgorio ruidoso y desordenado");
            yield return (674, "Pajolero", "Que produce molestia o enfado");
            yield return (675, "Paladino", "Público, claro y sin reservas");
            yield return (676, "Palimpsesto", "Códice raspado para poder escribir de nuevo sobre él, Corrección en un escrito");
            yield return (677, "Palinodia", "Retractación pública");
            yield return (678, "Palmaria", "Evidente");
            yield return (679, "Palpebral", "Relativo a los párpados");
            yield return (680, "Pampirolada", "Insustancial, Necedad");
            yield return (681, "Panacea", "Remedio");
            yield return (682, "Paralogismo", "Razonamiento falso, Sofisma");
            yield return (683, "Partenogénesis", "Reproducción asexual en la que no interviene el macho");
            yield return (684, "Patatús", "Lipotimia");
            yield return (685, "Patena", "Recipiente litúrgico donde se deposita el pan destinado a la consagración");
            yield return (686, "Patibulario", "Que por su repugnante aspecto produce horror o espanto");
            yield return (687, "Pátina", "Aspecto que toman algunos objetos con el tiempo");
            yield return (688, "Patochada", "Dicho u hecho inoportuno, necio u ofensivo");
            yield return (689, "Patraña", "Embuste");
            yield return (690, "Pazguato", "El que se escandaliza por cualquier cosa");
            yield return (691, "Peán", "Canto griego que se realizaba antes del combate o del convite");
            yield return (692, "Pechar", "Asumir responsabilidades u obligaciones que no son del agrado de uno");
            yield return (693, "Pedáneo", "Dícese de las autoridades administrativas cuya jurisdicción se extiende a aldeas");
            yield return (694, "Pedúnculo", "Tallo alargado que une un pequeño órgano terminal con el conjunto del cuerpo");
            yield return (695, "Pelagatos", "Persona con escasos recursos económicos");
            yield return (696, "Pelele", "Muñeco de figura humana, Persona de poco carácter");
            yield return (697, "Pendentif", "Adorno o joya que se lleva pendiente del cuello");
            yield return (698, "Pendón", "Bandera, Persona de vida desordenada");
            yield return (699, "Perdulario", "Que es muy descuidado con su persona o sus bienes, Vicioso");
            yield return (700, "Perendengue", "Adorno de poco valor");
            yield return (701, "Perentorio", "Urgente");
            yield return (702, "Pergueñar", "Ejecutar algo de manera no completa ni perfecta");
            yield return (703, "Periclitar", "Declinar, decaer");
            yield return (704, "Perico", "Espárrago de gran tamaño, Nombre de una especie de loro, Vela del palo de mesana, Orinal");
            yield return (705, "Perillán", "Granuja, Acicalado");
            yield return (706, "Perogrullada", "Verdad palmaria, evidente, obvia y que no necesita demostración");
            yield return (707, "Pertinaz", "Duradero, persistente");
            yield return (708, "Petimetre", "Lechugino, Hortera");
            yield return (709, "Picio", "Personaje de la antigüedad, famoso por su fealdad");
            yield return (710, "Pignorar", "Empeñar");
            yield return (711, "Piltrafa", "Residuos o trozos inaprovechables, especialmente de carne");
            yield return (712, "Pimplar", "Beber en exceso");
            yield return (713, "Pindonga", "Mujer que callejea");
            yield return (714, "Pintamonas", "Pintor malo");
            yield return (715, "Pintiparar", "Comparar una cosa con otra");
            yield return (716, "Piógeno", "Que forma pus");
            yield return (717, "Piorrea", "Enfermedad de las encías");
            yield return (718, "Píramo y Tisbe", "Famosos amantes de la antigüedad, Sólo podían verse por los resquicios del muro que separaba sus hogares");
            yield return (719, "Pitiminí", "Variedad de rosal de flores pequeñas");
            yield return (720, "Pleonasmo", "Uso de palabras innecesarias para dar más fuerza a la expresión");
            yield return (721, "Pluto", "Dios griego de las riquezas");
            yield return (722, "Plutócrata", "Gobierno de los más pudientes");
            yield return (723, "Pólipo", "Masa de aspecto tumoral y consistencia blanda");
            yield return (724, "Popelín", "Tela con urdimbre de seda y trama de algodón");
            yield return (725, "Portañuela", "Tira de tela con la que se tapa la bragueta de los pantalones");
            yield return (726, "Pósito", "Institución de carácter municipal destinada al almacén de alimentos para épocas de necesidad");
            yield return (727, "Postor", "Persona que licita");
            yield return (728, "Potranco", "Potro de menos de tres años");
            yield return (729, "Pragmático", "Persona práctica");
            yield return (730, "Prebenda", "Renta aneja a una canonjía u otras dignidades eclesiásticas, Oficio lucrativo y de poco trabajo");
            yield return (731, "Preboste", "Persona cabeza o jefe de alguna comunidad");
            yield return (732, "Preconizar", "Recomendar o aconsejar con intensidad una cosa de interés general");
            yield return (733, "Prestatario", "Persona que toma dinero a préstamo");
            yield return (734, "Prevaricar", "Faltar voluntariamente a la obligación del cargo que desempeña");
            yield return (735, "Prez", "Honor que se adquiere con una acción meritoria");
            yield return (736, "Probóscide", "Apéndice nasal del elefante");
            yield return (737, "Proemio", "Preludio de un canto");
            yield return (738, "Progenie", "Casta, generación o familia de la cual desciende alguien");
            yield return (739, "Prolijo", "Excesivamente extenso y detallado, Pesado, molesto");
            yield return (740, "Prorrateo", "Reparto proporcional de una cantidad");
            yield return (741, "Prosapia", "Alcurnia, linaje");
            yield return (742, "Prosodia", "Recta acentuación y pronunciación de sílabas y palabras");
            yield return (743, "Prosternarse", "Arrodillarse ante alguien en señal de respeto");
            yield return (744, "Psique", "Parte inmaterial del organismo, Mente");
            yield return (745, "Pucherazo", "Fraude electoral");
            yield return (746, "Puérpera", "Mujer recién parida");
            yield return (747, "Pugna", "Lucha");
            yield return (748, "Pústula", "Vesícula que contiene pus");
            yield return (749, "Putativo", "Tenido por padre, hermano, etc, no siéndolo");
            yield return (750, "Quincalla", "Artículo metálico de escaso valor");
            yield return (751, "Quorum", "Número de miembros requeridos en una asamblea para que sean válidos los acuerdos en ella obtenidos");
            yield return (752, "Rabadán", "Pastor a las órdenes del mayoral que gobierna uno o más rebaños");
            yield return (753, "Rada", "Bahía o ensenada protegida");
            yield return (754, "Razzia", "Incursión con el fin de obtener botín");
            yield return (755, "Rebato", "Llamamiento hecho a la gente cuando sobreviene un peligro");
            yield return (756, "Recalcitrante", "Obstinado");
            yield return (757, "Recipiendario", "El que es recibido solemnemente en una congregación para formar parte de ella");
            yield return (758, "Recoleto", "Lugar apartado");
            yield return (759, "Refacción", "Comida ligera");
            yield return (760, "Refocilar", "Divertir groseramente");
            yield return (761, "Refrigerio", "Refacción");
            yield return (762, "Regodeo", "Alegrarse malignamente con un daño o mala situación de otro");
            yield return (763, "Reinícola", "Habitante de un estado");
            yield return (764, "Reminiscencia", "Recuerdo vago e incompleto");
            yield return (765, "Réprobo", "Condenado a las penas del infierno");
            yield return (766, "Resol", "Reverberación del sol");
            yield return (767, "Retén", "Conjunto de gente dispuesto para un caso de necesidad");
            yield return (768, "Reverberación", "Reflexión intensa de las radiaciones luminosas, especialmente en la nieve");
            yield return (769, "Ripio", "Palabras de relleno en algún discurso, escrito u poema");
            yield return (770, "Roña", "Porquería, suciedad fuertemente incrustada en una superficie");
            yield return (771, "Rozagante", "Vistoso y de gran apariencia");
            yield return (772, "Sacamantecas", "Criminal que destripa a sus víctimas");
            yield return (773, "Sagrario", "Parte interior de un templo en el que se preservan las cosas sagradas");
            yield return (774, "Senectud", "Ancianidad");
            yield return (775, "Señero", "Notorio, Mejor que la generalidad");
            yield return (776, "Sicastenia", "Disminución del rendimiento por falta de impulso síquico");
            yield return (777, "Sicofanta", "Delator");
            yield return (778, "Simonía", "Tráfico de objetos o cargos eclesiásticos");
            yield return (779, "Sindéresis", "Buen juicio");
            yield return (780, "Síndico", "Persona encargada de representar y defender los intereses de una comunidad de habitantes");
            yield return (781, "Sine die", "Indefinidamente");
            yield return (782, "Sinecura", "Empleo retribuido que origina poco o ningún trabajo");
            yield return (783, "Sobrepujar", "Exceder una persona u cosa a otra en la cualidad de la que se trata");
            yield return (784, "Socaliña", "Ardid o petición insistente con la que se saca a alguien algo que no está obligado a dar");
            yield return (785, "Sodoma y Gomorra", "Ciudades Israelitas destruidas por Yahvé, Sodoma fue destruida por pecados sexuales sin identificar, Gomorra por quedar cerca, La oscuridad de la Biblia sobre este punto ha permitido las más diversas interpretaciones");
            yield return (786, "Sodomía", "El término puede significar desde bestialidad hasta homosexualidad, pasando por cualesquier actividad sexual no específicamente dedicada a la reproducción. Su acepción más común, en la actualidad es coito anal.");
            yield return (787, "Sofión", "Bufido");
            yield return (788, "Soflama", "Arenga");
            yield return (789, "Solano", "Viento del este");
            yield return (790, "Soma", "Parte material u orgánica del cuerpo");
            yield return (791, "Soponcio", "Desmayo");
            yield return (792, "Sosia", "Persona que se le parece tanto a otra que podría confundirse con ella");
            yield return (793, "Subrepticio", "Que se hace o se toma ocultamente o a escondidas");
            yield return (794, "Subrogar", "Sustituir a alguien o algo en una relación jurídica");
            yield return (795, "Subterfugio", "Evasiva, Pretexto");
            yield return (796, "Subvertir", "Trastornar");
            yield return (797, "Summum", "El máximo grado");
            yield return (798, "Supino", "Falta absoluta de conocimiento");
            yield return (799, "Suripanta", "Corista de teatro");
            yield return (800, "Tabuco", "Cuchitril");
            yield return (801, "Tálamo", "Lecho conyugal");
            yield return (802, "Talasocracia", "Dominio de los mares");
            yield return (803, "Tara", "Estigma, defecto");
            yield return (804, "Tarugo", "Zoquete");
            yield return (805, "Testaferro", "Persona que presta su nombre en un contrato que en realidad corresponde a otra persona");
            yield return (806, "Tetrafalangarcia", "División teórica de un ejército, contando 16, 384 hombres (214)");
            yield return (807, "Tétrico", "Lúgubre");
            yield return (808, "Tornasol", "Reflejo que hace la luz en algunas telas u otras sustancias");
            yield return (809, "Tóxico", "Ponzoña");
            yield return (810, "Tránsfuga", "Que cambia de un partido a otro");
            yield return (811, "Trapacería", "Fraude, engaño");
            yield return (812, "Trapisonda", "Discusión o riña violenta");
            yield return (813, "Traquido", "Ruido seco y fuerte ocasionado por el disparo de un arma de fuego");
            yield return (814, "Trebejo", "Utensilio");
            yield return (815, "Trepanar", "Horadar la cavidad craneal");
            yield return (816, "Triduo", "Período de tres días dedicado a un culto religioso");
            yield return (817, "Turíbulo", "Incensario");
            yield return (818, "Turma", "Testículo");
            yield return (819, "Tusígeno", "Que provoca la tos");
            yield return (820, "Ubérrimo", "Extremadamente fertil");
            yield return (821, "Ubicuo", "Que está en todas partes");
            yield return (822, "Ucronía", "Utopía aplicada a la historia, Reconstrucción histórica del modo en como podría ser y no ha sido");
            yield return (823, "Ulano", "Regimiento de lanceros a caballo");
            yield return (824, "Unigénito", "Hijo único");
            yield return (825, "Uruk", "Lagash, Umma, Ur, Ciudades-estado Sumerias");
            yield return (826, "Uxoricidio", "Delito que comete el que mata a su mujer");
            yield return (827, "Vademécum", "Tratado breve que contiene las nociones elementales de una ciencia u arte");
            yield return (828, "Vagido", "Llanto de un recién nacido");
            yield return (829, "Vanagloria", "Presunción o jactancia de una cualidad");
            yield return (830, "Venal", "Que se deja corromper o sobornar con dádivas");
            yield return (831, "Venero", "Manantial de agua, Aquello que origina o contiene gran cantidad de algo");
            yield return (832, "Venial", "Que es de fácil perdón");
            yield return (833, "Verbigracia", "Por ejemplo");
            yield return (834, "Verbosidad", "Tendencia a emplear más palabras de las necesarias para expresarse");
            yield return (835, "Verdolaga", "Hierba de hojas comestibles");
            yield return (836, "Verdugón", "Señal colorada o hinchada que dejan en el cuerpo los azotes");
            yield return (837, "Vertiginoso", "Que causa vértigo");
            yield return (838, "Vesania", "Demencia o furia intensa");
            yield return (839, "Vesical", "De la vejiga");
            yield return (840, "Vesicante", "Sustancia que produce ampollas en la piel");
            yield return (841, "Vestiglo", "Monstruo horrible y fantástico");
            yield return (842, "Vilipendio", "Humillación, deshonra o desprecio");
            yield return (843, "Villorrio", "Población falta de comodidades");
            yield return (844, "Vindicar", "Vengar, tomar satisfacción de un agravio");
            yield return (845, "Vislumbre", "Reflejo o débil resplandor de una luz, Visión muy corta de algo");
            yield return (846, "Vitela", "Pergamino muy blanco y flexible, hecha de las pieles de becerros recién nacidos");
            yield return (847, "Vitriolo", "Ácido sulfúrico concentrado");
            yield return (848, "Vituperar", "Censurar, reprimir, criticar");
            yield return (849, "Volatería", "Conjunto de aves de diversas especies, en gastronomía");
            yield return (850, "Volición", "Acto de voluntad que se manifiesta en la acción");
            yield return (851, "Zafarrancho", "Acción de desmbarazar alguna parte de la embarcación para dejarla dispuesta para alguna acción subsiguiente");
            yield return (852, "Zaino", "Traidor, falso, poco digno de confianza");
            yield return (853, "Zamacuco", "Persona que disimulando, hace siempre su voluntad");
            yield return (854, "Zambombo", "Zamacuco");
            yield return (855, "Zampabollos", "Glotón");
            yield return (856, "Zonzo", "Soso, insulso");
            yield return (857, "Zote", "Persona torpe e ignorante");
        }
    }
}
